export default {
  "styles": ["ipa", "la", "es", "en", "ru", "ja", "pd", "native0", "native1", "native2", "native3"],
  "sounds": [
    { "features": ["bilabial", "nasal"],
      "symbols": ["m",  "m",  "m",  "m",  "м",  "m",  "m",  "m",  "m",  "m",  "m"] },
    { "features": ["bilabial", "stop", "voiceless"],
      "symbols": ["p",  "p",  "p",  "p",  "п",  "p",  "p",  "p",  "p",  "p",  "p"] },
    { "features": ["bilabial", "stop"],
      "symbols": ["b",  "b",  "b",  "b",  "б",  "b",  "b",  "b",  "b",  "b",  "b"] },
    { "features": ["bilabial", "fricate", "voiceless"],
      "symbols": ["ɸ",  "ph", "f",  "f",  "ф",  "f",  "ph", "f",  "f",  "f",  "f"] },
    { "features": ["bilabial", "fricate"],
      "symbols": ["β",  "b",  "b",  "v",  "в",  "v",  "bh", "v",  "v",  "v",  "ƀ"] },
    { "features": ["bilabial", "trill"],
      "symbols": ["ʙ",  "b",  "br", "pbr","бв", "bur","br", "bb", "br", "bb", "blr"] },
    { "features": ["bilabial", "trill", "breathy"],
      "symbols": ["ʙ̝",  "b",  "br", "pbr","бв", "bur","br", "bbv","bř", "b̌",  "blř"] },
    { "features": ["labiodental", "nasal"],
      "symbols": ["ɱ",  "m",  "m",  "m",  "м",  "m",  "m",  "m",  "m",  "m",  "m"] },
    { "features": ["labiodental", "stop", "voiceless"],
      "symbols": ["p͆",  "p",  "p",  "p",  "п",  "p",  "p",  "p",  "p",  "p",  "p"] },
    { "features": ["labiodental", "stop"],
      "symbols": ["b̪",  "b",  "b",  "b",  "б",  "b",  "b",  "b",  "b",  "b",  "b"] },
    { "features": ["labiodental", "fricate", "voiceless"],
      "symbols": ["f",  "f",  "f",  "f",  "ф",  "f",  "f",  "f",  "f",  "f",  "f"] },
    { "features": ["labiodental", "fricate"],
      "symbols": ["v",  "v",  "v",  "v",  "в",  "v",  "v",  "v",  "v",  "v",  "v"] },
    { "features": ["labiodental", "close"],
      "symbols": ["ʋ",  "v",  "u",  "w",  "в",  "w",  "v",  "v",  "w",  "v",  "w"] },
    { "features": ["labiodental", "tap"],
      "symbols": ["ⱱ",  "v",  "u",  "v",  "в",  "w",  "v",  "vw", "vw", "vw", "vw"] },
    { "features": ["dental", "nasal"],
      "symbols": ["n",  "n",  "n",  "n",  "н",  "n",  "n",  "n",  "n",  "n",  "n"] },
    { "features": ["dental", "stop", "voiceless"],
      "symbols": ["t",  "t",  "t",  "t",  "т",  "t",  "t",  "t",  "t",  "t",  "t"] },
    { "features": ["dental", "stop"],
      "symbols": ["d",  "d",  "d",  "d",  "д",  "d",  "d",  "d",  "d",  "d",  "d"] },
    { "features": ["dental", "fricate", "voiceless"],
      "symbols": ["θ",  "th", "z",  "th", "ф",  "s",  "th", "th", "th", "ṯ",  "ŧ"] },
    { "features": ["dental", "fricate"],
      "symbols": ["ð",  "d",  "d",  "th", "д",  "z",  "dh", "dh", "dh", "ḏ",  "đ"] },
    { "features": ["alveolar", "affricate", "voiceless"],
      "symbols": ["t͡s", "c",  "z",  "tz", "ц",  "c",  "ch", "ts", "tz", "c",  "z"] },
    { "features": ["alveolar", "affricate"],
      "symbols": ["d͡z", "z",  "z",  "z",  "дз", "ッz", "z",  "dz", "dz", "dz", "z"] },
    { "features": ["alveolar", "fricate", "voiceless"],
      "symbols": ["s",  "s",  "s",  "s",  "с",  "s",  "s",  "s",  "s",  "s",  "s"] },
    { "features": ["alveolar", "fricate"],
      "symbols": ["z",  "z",  "z",  "z",  "з",  "z",  "z",  "z",  "z",  "z",  "z"] },
    { "features": ["postalveolar", "affricate", "voiceless"],
      "symbols": ["t͡ʃ", "sc",  "ch", "ch", "ч",  "q",  "ch", "tsh","ch", "č",  "c"] },
    { "features": ["postalveolar", "affricate"],
      "symbols": ["d͡ʒ", "j",  "y",  "j",  "дж", "j",  "j",  "dzh","j",  "dž", "j"] },
    { "features": ["postalveolar", "fricate", "voiceless"],
      "symbols": ["ʃ",  "sc", "s",  "sh", "ш",  "sy", "sh", "sh", "sh", "š",  "x"] },
    { "features": ["postalveolar", "fricate"],
      "symbols": ["ʒ",  "z",  "y",  "j",  "ж",  "zy", "zh", "zh", "zh", "ž",  "j"] },
    { "features": ["dental", "affricate", "voiceless", "lateral"],
      "symbols": ["t͡ɬ", "cl", "cl", "cl", "тл", "tor","tl", "tl", "tl", "tl", "kl"] },
    { "features": ["dental", "affricate", "lateral"],
      "symbols": ["d͡ɮ", "gl", "gl", "gl", "дл", "dor","dl", "dl", "dl", "dl", "gl"] },
    { "features": ["dental", "fricate", "voiceless", "lateral"],
      "symbols": ["ɬ",  "l",  "l",  "fl", "сл", "r",  "l",  "ll", "sl", "lh", "hl"] },
    { "features": ["dental", "fricate", "lateral"],
      "symbols": ["ɮ",  "l",  "l",  "ll", "зл", "r",  "l",  "dl", "zl", "zl", "dl"] },
    { "features": ["dental", "close"],
      "symbols": ["ɹ",  "r",  "r",  "r",  "р",  "r",  "r",  "r",  "r",  "r",  "r"] },
    { "features": ["dental", "close", "lateral"],
      "symbols": ["l",  "l",  "l",  "l",  "л",  "r",  "l",  "l",  "l",  "l",  "l"] },
    { "features": ["dental", "close", "lateral", "velarized"],
      "symbols": ["ɫ",  "l",  "l",  "l",  "ль", "r",  "l",  "gl", "ll", "l",  "ł"] },
    { "features": ["dental", "trill"],
      "symbols": ["r",  "r",  "r",  "r",  "р",  "r",  "r",  "r",  "r",  "r",  "r"] },
    { "features": ["dental", "trill", "breathy"],
      "symbols": ["r̝",  "r",  "rr", "rz", "рж", "ruz","r",  "rz", "ř",  "ř",  "ř"] },
    { "features": ["dental", "tap"],
      "symbols": ["ɾ",  "r",  "r",  "r",  "р",  "r",  "r",  "r",  "r",  "r",  "r"] },
    { "features": ["dental", "tap","lateral"],
      "symbols": ["ɺ",  "r",  "r",  "l",  "р",  "r",  "l",  "lr", "r",  "ṛ",  "r"] },
    { "features": ["retroflex", "nasal"],
      "symbols": ["ɳ",  "n",  "n",  "n",  "н",  "n",  "n",  "ṇ",  "rn", "ṇ",  "nh"] },
    { "features": ["retroflex", "stop", "voiceless"],
      "symbols": ["ʈ",  "t",  "t",  "t",  "т",  "t",  "t",  "ṭ",  "tr", "ṭ",  "ṭ"] },
    { "features": ["retroflex", "stop"],
      "symbols": ["ɖ",  "d",  "d",  "d",  "д",  "d",  "d",  "ḍ",  "dr", "ḍ",  "ḍ"] },
    { "features": ["retroflex", "affricate", "voiceless"],
      "symbols": ["ʈ͡ʂ", "sc",  "ch", "ch", "ч",  "q",  "c",  "tṣ", "ch", "cz", "ch"] },
    { "features": ["retroflex", "affricate"],
      "symbols": ["ɖ͡ʐ", "j",  "y",  "j",  "дж", "j",  "j",  "dẓ", "j",  "drz","zh"] },
    { "features": ["retroflex", "fricate", "voiceless"],
      "symbols": ["ʂ",  "sc", "s",  "sh", "ш",  "sy", "sh", "ṣ",  "sh", "sz", "sh"] },
    { "features": ["retroflex", "fricate"],
      "symbols": ["ʐ",  "r",  "y",  "j",  "ж",  "zy", "zh", "ẓ",  "zh", "rz", "zh"] },
    { "features": ["retroflex", "fricate", "voiceless", "lateral"],
      "symbols": ["ꞎ",  "l",  "l",  "fl", "л",  "r",  "l",  "ll", "rl", "ꞎ",  "hlh"] },
    { "features": ["retroflex", "fricate", "lateral"],
      "symbols": ["ɭ˔", "l",  "l",  "ll", "зл", "r",  "l",  "dl", "zl", "zl", "dl"] },
    { "features": ["retroflex", "close"],
      "symbols": ["ɻ",  "r",  "r",  "r",  "р",  "r",  "r",  "r",  "r",  "ṛ",  "rh"] },
    { "features": ["retroflex", "close", "lateral"],
      "symbols": ["ɭ",  "l",  "l",  "l",  "л",  "r",  "l",  "ḷ",  "rl", "ḷ",  "lh"] },
    { "features": ["retroflex", "tap"],
      "symbols": ["ɽ",  "r",  "r",  "r",  "р",  "r",  "r",  "r",  "r",  "ṛ",  "rh"] },
    { "features": ["palatal", "nasal"],
      "symbols": ["ɲ",  "gn", "ñ",  "ny", "нь", "ny", "ny", "ny", "nh", "ñ",  "ny"] },
    { "features": ["palatal", "stop", "voiceless"],
      "symbols": ["c",  "cj", "cy", "c",  "кь", "ky", "ky", "ky", "k",  "tj", "k"] },
    { "features": ["palatal", "stop"],
      "symbols": ["ɟ",  "j",  "y",  "j",  "гь", "gy", "gy", "gy", "g",  "dj", "g"] },
    { "features": ["palatal", "fricate", "voiceless"],
      "symbols": ["ç",  "hj", "jy", "sh", "щ",  "hy", "hy", "hy", "sh", "sj", "h"] },
    { "features": ["palatal", "fricate"],
      "symbols": ["ʝ",  "j",  "y",  "y",  "й",  "y",  "y",  "y",  "y",  "j",  "y"] },
    { "features": ["palatal", "fricate", "voiceless", "lateral"],
      "symbols": ["ʎ̥",  "hj", "ll", "sh", "щ",  "hy", "hy", "lly","shl","lhj","ły"] },
    { "features": ["palatal", "fricate", "lateral"],
      "symbols": ["ʎ̝",  "j",  "ll", "j",  "ж",  "zy", "j",  "dly","zhl","hlj","y"] },
    { "features": ["palatal", "close", "lateral"],
      "symbols": ["ʎ",  "gl", "ll", "y",  "ль", "ry", "ly", "ly", "lh", "lj", "ly"] },
    { "features": ["velar", "nasal"],
      "symbols": ["ŋ",  "n",  "n",  "ng", "нг", "ⁿg", "ng", "ng", "ñ",  "ng", "ng"] },
    { "features": ["velar", "stop", "voiceless"],
      "symbols": ["k",  "c",  "c",  "c",  "к",  "k",  "k",  "k",  "k",  "k",  "k"] },
    { "features": ["velar", "stop"],
      "symbols": ["ɡ",  "g",  "g",  "g",  "г",  "g",  "g",  "g",  "g",  "g",  "g"] },
    { "features": ["velar", "fricate", "voiceless"],
      "symbols": ["x",  "ch", "j",  "gh", "х",  "h",  "kh", "h",  "kh", "x",  "kh"] },
    { "features": ["velar", "fricate"],
      "symbols": ["ɣ",  "g",  "g",  "g",  "г",  "g",  "gh", "gh", "gh", "ğ",  "ğ"] },
    { "features": ["velar", "fricate", "voiceless", "lateral"],
      "symbols": ["ʟ̥",  "l",  "ll", "sl", "хл", "hy", "hl", "ll", "khl","lwh","khl"] },
    { "features": ["velar", "fricate", "lateral"],
      "symbols": ["ʟ̝",  "l",  "ll", "gl", "гл", "zy", "l",  "gl", "ghl","ğl", "ɣl"] },
    { "features": ["velar", "close", "lateral"],
      "symbols": ["ʟ",  "l",  "ll", "y",  "ль", "ry", "l",  "lw", "lw", "lw", "lw"] },
    { "features": ["uvular", "nasal"],
      "symbols": ["ɴ",  "n",  "n",  "ng", "н",  "ン",  "ng", "ng", "ñ",  "ng", "ng"] },
    { "features": ["uvular", "stop", "voiceless"],
      "symbols": ["q",  "g",  "g",  "c",  "г",  "k",  "q",  "q",  "q",  "q",  "q"] },
    { "features": ["uvular", "stop"],
      "symbols": ["ɢ",  "g",  "g",  "g",  "г",  "g",  "g",  "gh", "q",  "q",  "q"] },
    { "features": ["uvular", "fricate", "voiceless"],
      "symbols": ["χ",  "ch", "j",  "ɦ",  "х",  "h",  "qh", "qh", "h",  "x̌", "qh"] },
    { "features": ["uvular", "fricate"],
      "symbols": ["ʁ",  "r",  "r",  "r",  "р",  "r",  "rh", "r",  "rh", "r",  "r"] },
    { "features": ["uvular", "trill"],
      "symbols": ["ʀ",  "r",  "r",  "r",  "р",  "r",  "r",  "r",  "r",  "r",  "r"] },
    { "features": ["epiglottal", "stop"],
      "symbols": ["ʡ",  "g",  "g",  "c",  "г",  "k",  "k",  "q̇",  "q",  "q̇",  "q̇"] },
    { "features": ["epiglottal", "fricate", "voiceless"],
      "symbols": ["ħ",  "h",  "j",  "ɦ",  "х",  "h",  "h",  "ḥ",  "h",  "ḥ",  "ḥ"] },
    { "features": ["epiglottal", "fricate"],
      "symbols": ["ʕ",  "",   "h",  "",   "",   "",   "",   "g’", "ʻ",  "ʻ",  "ʻ"] },
    { "features": ["glottal", "stop", "voiceless"],
      "symbols": ["ʔ",  "",   "h",  "",   "",   "",   "",   "’",  "’",  "ʻ",  "’"] },
    { "features": ["glottal", "fricate", "voiceless"],
      "symbols": ["h",  "h",  "j",  "ɦ",  "г",  "h",  "h",  "h",  "h",  "h",  "h"] },
    { "features": ["bilabial", "click", "voiceless"],
      "symbols": ["ᵏʘ", "p",  "pop","pw", "кп", "ッp", "p",  "cp", "cp", "ʘ", "cp"] },
    { "features": ["bilabial", "click"],
      "symbols": ["ᶢʘ", "b",  "bop","mw", "кб", "ッp", "b",  "gp", "gp", "gʘ", "gp"] },
    { "features": ["alveolar", "click", "voiceless"],
      "symbols": ["ᵏǀ", "t",  "tut","tut","кт", "ッt", "t",  "c",  "c",  "ǀ",  "c"] },
    { "features": ["alveolar", "click"],
      "symbols": ["ᶢǀ", "d",  "dut","dut","кд", "ッt", "d",  "gc", "gc", "gǀ", "gc"] },
    { "features": ["palatal", "click", "voiceless"],
      "symbols": ["ᵏǂ", "c",  "ket","cit","кк", "ッk", "k",  "cy", "ç",  "ǂ",  "ç"] },
    { "features": ["palatal", "click"],
      "symbols": ["ᶢǂ", "c",  "get","git","кг", "ッk", "g",  "gcy","gç", "gǂ", "gç"] },
    { "features": ["palatal", "click", "voiceless", "lateral"],
      "symbols": ["ᵏǁ", "cl", "tec","tic","тк", "ッk", "k",  "x",  "x",  "ǁ",  "x"] },
    { "features": ["palatal", "click", "lateral"],
      "symbols": ["ᶢǁ", "gl", "dec","dic","тг", "ッk", "g",  "gx", "gx", "gǁ", "gx"] },
    { "features": ["retroflex", "click", "voiceless"],
      "symbols": ["ᵏǃ", "t",  "tac","tac","тт", "ッt", "t",  "q",  "q",  "ǃ",  "q"] },
    { "features": ["retroflex", "click"],
      "symbols": ["ᶢǃ", "t",  "dac","dac","тд", "ッt", "t",  "gq", "gq", "gǃ", "gq"] },
    { "features": ["palatal", "close"],
      "symbols": ["j",  "j",  "y",  "y",  "й",  "y",  "y",  "y",  "y",  "j",  "y"] },
    { "features": ["palatal", "close", "rounded"],
      "symbols": ["ɥ",  "j",  "yu", "yu*","ю",  "yu", "yu", "yu", "yu", "y",  "w"] },
    { "features": ["velar", "close"],
      "symbols": ["ɰ",  "v",  "u",  "w",  "у",  "w",  "v",  "w",  "w",  "w",  "w"] },
    { "features": ["velar", "close", "rounded"],
      "symbols": ["w",  "v",  "u",  "w",  "в",  "w",  "v",  "w",  "w",  "w",  "w"] },
    { "features": ["palatal", "close", "vowel"],
      "symbols": ["i",  "i",  "i",  "e–", "и",  "i",  "i",  "i",  "i",  "i",  "i"] },
    { "features": ["palatal", "close", "vowel", "rounded"],
      "symbols": ["y",  "y",  "i",  "u–", "ю",  "yu", "i",  "ü",  "oi", "y",  "ʉ"] },
    { "features": ["central", "close", "vowel"],
      "symbols": ["ɨ",  "y",  "i",  "i*", "ы",  "i",  "i",  "ï",  "i",  "ị",  "ɨ"] },
    { "features": ["central", "close", "vowel", "rounded"],
      "symbols": ["ʉ",  "y",  "u",  "u*", "ю",  "u",  "u",  "ü",  "u",  "ụ",  "ʉ"] },
    { "features": ["velar", "close", "vowel"],
      "symbols": ["ɯ",  "u",  "u",  "ɯ–", "ы",  "u",  "u",  "ï",  "eu", "ị",  "ü"] },
    { "features": ["velar", "close", "vowel", "rounded"],
      "symbols": ["u",  "u",  "u",  "ɯ–", "у",  "u",  "u",  "u",  "u",  "u",  "u"] },
    { "features": ["palatal", "near close", "vowel"],
      "symbols": ["ɪ",  "i",  "i",  "i*", "и",  "i",  "i",  "i",  "i",  "ị",  "i"] },
    { "features": ["palatal", "near close", "vowel", "rounded"],
      "symbols": ["ʏ",  "y",  "i",  "yu*","ю",  "yu", "i",  "ü",  "oi", "ỵ",  "ʉ"] },
    { "features": ["central", "near close", "vowel"],
      "symbols": ["ɨ̞",  "y",  "i",  "i*", "ы",  "i",  "i",  "ï",  "i",  "ị",  "ɨ"] },
    { "features": ["central", "near close", "vowel", "rounded"],
      "symbols": ["ʉ̞",  "y",  "u",  "u*", "ю",  "u",  "u",  "ü",  "u",  "ụ",  "ʉ"] },
    { "features": ["velar", "near close", "vowel"],
      "symbols": ["ɯ̞",  "u",  "u",  "ɯ–", "ы",  "u",  "u",  "ï",  "eu", "ị",  "ü"] },
    { "features": ["velar", "near close", "vowel", "rounded"],
      "symbols": ["ʊ",  "u",  "u",  "u*", "у",  "u",  "u",  "u",  "u",  "ụ",  "u"] },
    { "features": ["palatal", "close mid", "vowel"],
      "symbols": ["e",  "e",  "e",  "a–", "э",  "e",  "e",  "e",  "e",  "e",  "e"] },
    { "features": ["palatal", "close mid", "vowel", "rounded"],
      "symbols": ["ø",  "œ",  "e",  "ɯ*r","ё",  "e",  "e",  "ö",  "oe", "ẹ",  "œ"] },
    { "features": ["central", "close mid", "vowel"],
      "symbols": ["ɘ",  "e",  "e",  "ɯ*", "а",  "a",  "e",  "ë",  "y",  "ạ",  "ə"] },
    { "features": ["central", "close mid", "vowel", "rounded"],
      "symbols": ["ɵ",  "œ",  "o",  "ɯ*r","о",  "o",  "o",  "ö",  "y",  "ạ",  "ə"] },
    { "features": ["velar", "close mid", "vowel"],
      "symbols": ["ɤ",  "o",  "e",  "ɯ*", "ы",  "o",  "o",  "ë",  "eo", "ọ",  "ö"] },
    { "features": ["velar", "close mid", "vowel", "rounded"],
      "symbols": ["o",  "o",  "o",  "o–", "о",  "o",  "o",  "o",  "o",  "o",  "o"] },
    { "features": ["palatal", "open mid", "vowel"],
      "symbols": ["ɛ",  "e",  "e",  "e*", "э",  "e",  "e",  "e",  "e",  "ẹ",  "e"] },
    { "features": ["palatal", "open mid", "vowel", "rounded"],
      "symbols": ["œ",  "œ",  "e",  "ɯ*r","ё",  "e",  "e",  "ö",  "oe", "ẹ",  "œ"] },
    { "features": ["palatal", "open mid"],
      "symbols": ["ə̯",  "e",  "e",  "r",  "а",  "e",  "e",  "ë",  "y",  "ạ",  "ə"] },
    { "features": ["central", "open mid", "vowel"],
      "symbols": ["ə",  "e",  "e",  "ɯ*", "а",  "a",  "e",  "ë",  "y",  "ạ",  "ə"] },
    { "features": ["central", "open mid", "vowel", "rounded"],
      "symbols": ["ɞ",  "œ",  "o",  "ɯ*r","о",  "o",  "o",  "ö",  "y",  "ọ",  "ə"] },
    { "features": ["velar", "open mid", "vowel"],
      "symbols": ["ʌ",  "o",  "e",  "ɯ*", "ы",  "o",  "o",  "ë",  "eo", "ọ",  "ö"] },
    { "features": ["velar", "open mid", "vowel", "rounded"],
      "symbols": ["ɔ",  "o",  "o",  "o*", "о",  "o",  "o",  "å",  "o",  "ọ",  "o"] },
    { "features": ["palatal", "near open", "vowel"],
      "symbols": ["æ",  "æ",  "a",  "a*", "э",  "a",  "a",  "ä",  "a",  "ạ",  "æ"] },
    { "features": ["central", "near open", "vowel"],
      "symbols": ["ɐ",  "a",  "a",  "ɯ*", "а",  "a",  "a",  "a",  "a",  "ạ",  "a"] },
    { "features": ["palatal", "open", "vowel"],
      "symbols": ["a",  "a",  "a",  "a*", "а",  "a",  "a",  "a",  "a",  "a",  "a"] },
    { "features": ["central", "open", "vowel"],
      "symbols": ["a",  "a",  "a",  "a*", "а",  "a",  "a",  "a",  "a",  "a",  "a"] },
    { "features": ["velar", "open", "vowel"],
      "symbols": ["ɑ",  "a",  "a",  "a*", "a",  "a",  "a",  "a",  "a",  "a",  "a"] },
    { "features": ["velar", "open", "vowel", "rounded"],
      "symbols": ["ɒ",  "o",  "o",  "o*", "о",  "o",  "o",  "å",  "a",  "ọ",  "a"] }
  ],
  "suprasegmentals": [
    { "name": "syllable break",
      "symbols": [".",  "",   "",   "",   "",   "",   "",   "",   "",   "",   ""] },
    { "name": "word break",
      "symbols": [" ",  " ",  " ",  " ",  "-",  "・",  " ",  " ",  " ",  " ",  "-"] }
  ],
  "modifiers": [
    { "name": "long",
      "symbols": ["Xː", "X̄",  "X",  "X",  "X",  "Xー", "X",  "xX", "Xh", "X",  "X̄"] },
    { "name": "geminate",
      "symbols": ["Xː", "xX", "X",  "xX", "xX", "ッX", "X",  "xX", "xX", "xX", "xX"] },
    { "name": "affricate",
      "symbols": ["X͡Y", "Y",  "Y",  "X",  "XY", "X",  "Y",  "XY", "XY", "XY", "XY"] },
    { "name": "aspirate",
      "symbols": ["Xʰ", "Xh", "X",  "X",  "Xх", "X",  "X",  "Xh", "Xh", "Xh", "Xh"] },
    { "name": "ejective",
      "symbols": ["Xʼ", "xX", "X",  "xX", "xX", "ッX", "X",  "Xʼ", "xX", "Xʼ", "Xʼ"] },
    { "name": "devoice",
      "symbols": ["X̥",  "Xh", "X",  "X",  "X",  "X",  "X",  "Xh", "Xh", "Xh", "Xh"] },
    { "name": "breathy",
      "symbols": ["X̤",  "X",  "X",  "X",  "Xх", "X",  "X",  "Xh", "Xh", "Xh", "Xh"] },
    { "name": "linguolab",
      "symbols": ["X̼",  "Y",  "Xl", "Xl", "лX", "Y",  "Y",  "Ẍ",  "Xl", "Ÿ",  "Ẍ"] },
    { "name": "double",
      "symbols": ["X͡Y", "yX", "Y",  "yX", "yX", "Y",  "Y",  "XY", "xY", "xY", "xY"] },
    { "name": "labializ",
      "symbols": ["Xʷ", "Xv", "Xu", "Xw", "Xу", "Xw", "Xy", "Xw", "Xw", "Xw", "X’"] },
    { "name": "palataliz",
      "symbols": ["Xʲ", "Xj", "Xi", "Xy", "Xь", "Xy", "Xw", "Xy", "Xy", "X’", "X’"] },
    { "name": "velariz",
      "symbols": ["Xˠ", "X",  "Xu", "X",  "Xь", "X",  "X",  "gX", "Xw", "X̴",  "X’"] },
    { "name": "pharyngealiz",
      "symbols": ["Xˤ", "X",  "X",  "X",  "X",  "X",  "X",  "X̣",  "X̰",  "Xʻ", "Xʻ"] },
    { "name": "nasaliz",
      "symbols": ["X̃",  "X",  "X",  "X",  "X",  "Xン", "Xn", "X̃",  "X̨",  "X̃",  "Ẍ"] },
    { "name": "prenasaliz",
      "symbols": ["x͡Y", "xY", "xY", "xY", "xY", "ンY", "xY", "xY", "xY", "Yx", "xY"] },
    { "name": "primary",
      "symbols": ["ˈX",  "X",  "X́",  "X",  "X́",  "X",  "X",  "X",  "X",  "X́",  "X"] },
    { "name": "secondary",
      "symbols": ["ˌX",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X"] },
    { "name": "glide",
      "symbols": ["X̯",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X̆",  "X"] },
    { "name": "syllabic",
      "symbols": ["X̩",  "X",  "eX", "eX", "X",  "X",  "oX", "X",  "X'", "X",  "X"] },
    { "name": "approx",
      "symbols": ["X̞",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X",  "X"] }
  ],
  "flags": [
    { "name": "capitalization",
      "values": [false, true, true, true, true, false, false, true, true, true, true] },
    { "name": "au as ao",
      "values": [false, false, false, false, false, false, false, false, true, false, false] },
    { "name": "diphthong as hiatus",
      "values": [false, true, false, true, false, false, true, true, true, true, false] },
    { "name": "velar nasal as coronal",
      "values": [false, true, true, true, true, true, true, true, false, true, false] },
    { "name": "chain nasalized vocoids",
      "values": [false, false, false, false, false, true, true, false, true, false, false] }
  ]
};
