export default [
    { "result": "u–", "patterns": ["yɯ–", "yu–"] },
    { "result": "nu–", "patterns": ["nɯ–"] },
    { "result": "tu–", "patterns": ["tɯ–"] },
    { "result": "du–", "patterns": ["dɯ–"] },
    { "result": "su–", "patterns": ["sɯ–"] },
    { "result": "zu–", "patterns": ["zɯ–"] },
    { "result": "shu–", "patterns": ["shɯ–"] },
    { "result": "chu–", "patterns": ["chɯ–"] },
    { "result": "ju–", "patterns": ["jɯ–"] },
    { "result": "ru–", "patterns": ["rɯ–"] },
    { "result": "lu–", "patterns": ["lɯ–"] },
    { "result": "sh", "patterns": ["shy"] },
    { "result": "ch", "patterns": ["chy"] },
    { "result": "j", "patterns": ["jy"] },
    { "result": "re–", "patterns": ["ry"] },
    { "result": "le–", "patterns": ["ly"] },
    { "result": "a*", "patterns": ["a*a*", "a*ɯ*"] },
    { "result": "i–", "patterns": ["a*e*", "a*i*", "a*a–", "a*e–", "a*i–", "a*y", "i–y", "ɯ*e–", "ɯ*i–", "ɯ*i*", "ɯ*y"] },
    { "result": "ow", "patterns": ["a*o*", "a*u*", "a*o–", "a*ɯ–", "o*ɯ–", "a*w", "i–w"] },
    { "result": "ayu–", "patterns": ["a*u–", "e*u–", "ɯ*u–"] },
    { "result": "eya*", "patterns": ["e*a*"] },
    { "result": "a–", "patterns": ["e*e*", "e*i*", "e*a–", "e*e–", "e*y", "a–y", "ɯ*a–"] },
    { "result": "ao*", "patterns": ["e*o*"] },
    { "result": "ai–", "patterns": ["e*i–"] },
    { "result": "ao–", "patterns": ["e*o–"] },
    { "result": "ew", "patterns": ["e*u*", "e*ɯ–", "e*w", "i*u*", "i*ɯ–", "i*ɯ–", "i*u–", "i*w", "a–w", "e–w"] },
    { "result": "ea*", "patterns": ["i*a*"] },
    { "result": "ee*", "patterns": ["i*e*"] },
    { "result": "e–", "patterns": ["i*i*", "i*e–", "i*i–", "i*y", "e–e–", "e–y"] },
    { "result": "eo*", "patterns": ["i*o*"] },
    { "result": "ea–", "patterns": ["i*a–"] },
    { "result": "eo–", "patterns": ["i*o–"] },
    { "result": "oa*", "patterns": ["o*a*", "o–ɯ*"] },
    { "result": "oy", "patterns": ["o*e*", "o*i*", "o*e–", "o*y", "o–y"] },
    { "result": "o–", "patterns": ["o*o*", "o*u*", "o*o–", "o*ɯ–", "o*w", "o–w", "ɯ*o–", "ɯ*u*", "ɯ*ɯ–", "ɯ*w"] },
    { "result": "oyu–", "patterns": ["o*u–"] },
    { "result": "oa–", "patterns": ["o*a–"] },
    { "result": "oi–", "patterns": ["o*i–"] },
    { "result": "ua*", "patterns": ["u*a*"] },
    { "result": "ue*", "patterns": ["u*e*"] },
    { "result": "ui*", "patterns": ["u*i*"] },
    { "result": "uo*", "patterns": ["u*o*"] },
    { "result": "ear", "patterns": ["e*ɯ*"] },
    { "result": "eer", "patterns": ["i*ɯ*"] },
    { "result": "o*", "patterns": ["o*ɯ*"] },
    { "result": "ur", "patterns": ["u*ɯ*"] },
    { "result": "ayu–", "patterns": ["ɯ*u–"] },
    { "result": "a*", "patterns": ["ɯ*a*"] },
    { "result": "e*", "patterns": ["ɯ*e*"] },
    { "result": "o*", "patterns": ["ɯ*o*"] },
    { "result": "ua–", "patterns": ["u*a–"] },
    { "result": "ue–", "patterns": ["u*e–", "u–y"] },
    { "result": "ooe–", "patterns": ["ɯ–e–", "ɯ–y", "u*y"] },
    { "result": "ui–", "patterns": ["u*i–"] },
    { "result": "uo–", "patterns": ["u*o–"] },
    { "result": "u–", "patterns": ["u*ɯ–", "u*w", "u–ɯ–", "u–u–", "u–w"] },
    { "result": "ooyu–", "patterns": ["u*u–"] },
    { "result": "e–", "patterns": ["ye–"] },
    { "result": "aia", "patterns": ["i-a*", "a-a*"] },
    { "result": "a#", "patterns": ["a*#", "ɯ*#"] },
    { "result": "o#", "patterns": ["o*#", "o–#"] },
    { "result": "ay#", "patterns": ["e*#", "a–#"] },
    { "result": "ooey#", "patterns": ["ɯ–i*#", "ɯ–e–#"] },
    { "result": "y#", "patterns": ["i*#", "e–#"] },
    { "result": "oo#", "patterns": ["u*#"] },
    { "result": "ia#", "patterns": ["i–#", "e–a#"] },
    { "result": "ve#", "patterns": ["v#"] },
    { "result": "je#", "patterns": ["j#"] },
    { "result": "dje#", "patterns": ["*je#"] },
    { "result": "ue#", "patterns": ["u–#"] },
    { "result": "ve#", "patterns": ["v#"] },
    { "result": "ia#", "patterns": ["ya#"] },
    { "result": "cia#", "patterns": ["sha#"] },
    { "result": "sia#", "patterns": ["ja#"] },
    { "result": "tia#", "patterns": ["cha#"] },
    { "result": "oo", "patterns": ["ɯ–", "u*ɯ–"] },
    { "result": "u*", "patterns": ["ɯ*", "u*u*", "ɯ*ɯ*"] },
    { "result": "*cc#", "patterns": ["*c#"] },
    { "result": "*ff#", "patterns": ["*f#"] },
    { "result": "*ll#", "patterns": ["*l#"] },
    { "result": "*ss#", "patterns": ["*s#"] },
    { "result": "*zz#", "patterns": ["*z#"] },
    { "result": "*cky#", "patterns": ["*cy#"] },
    { "result": "*ffy#", "patterns": ["*fy#"] },
    { "result": "*lly#", "patterns": ["*ly#"] },
    { "result": "*ssy#", "patterns": ["*sy#"] },
    { "result": "*zzy#", "patterns": ["*zy#"] }
];
//# sourceMappingURL=rules_en.js.map