export default {
  "techs": [
    {"year": -9999, "key": "undefined", "type": "boundary"},
    {"year": -9999, "key": "stone", "type": "material"},
    {"year": -9999, "key": "spear", "type": "fighting"},
    {"year": -9999, "key": "oil", "type": "lighting"},
    {"year": -3500, "key": "walking", "type": "movement"},
    {"year": -3200, "key": "dam", "type": "pasttime"},
    {"year": -3000, "key": "bronze", "type": "material"},
    {"year": -2500, "key": "glass", "type": "pasttime"},
    {"year": -1800, "key": "iron", "type": "material"},
    {"year": -1750, "key": "carriage", "type": "movement"},
    {"year": -1600, "key": "sword", "type": "fighting"},
    {"year": -1400, "key": "sundial", "type": "pasttime"},
    {"year":  -650, "key": "crossbow", "type": "fighting"},
    {"year":  -600, "key": "steel", "type": "material"},
    {"year":  -500, "key": "candle", "type": "lighting"},
    {"year":  -400, "key": "catapult", "type": "fighting"},
    {"year":  -200, "key": "defined", "type": "boundary"},
    {"year":  -150, "key": "saddle", "type": "movement"},
    {"year":   150, "key": "paper", "type": "pasttime"},
    {"year":   589, "key": "toilet", "type": "pasttime"},
    {"year":  1000, "key": "compass", "type": "pasttime"},
    {"year":  1250, "key": "firelance", "type": "fighting"},
    {"year":  1298, "key": "cannon", "type": "fighting"},
    {"year":  1400, "key": "clock", "type": "pasttime"},
    {"year":  1440, "key": "press", "type": "pasttime"},
    {"year":  1521, "key": "musket", "type": "fighting"},
    {"year":  1608, "key": "telescope", "type": "pasttime"},
    {"year":  1731, "key": "sextant", "type": "pasttime"},
    {"year":  1740, "key": "rifle", "type": "fighting"},
    {"year":  1769, "key": "car", "type": "movement"},
    {"year":  1813, "key": "gas", "type": "lighting"},
    {"year":  1861, "key": "machine_gun", "type": "fighting"},
    {"year":  1879, "key": "electricity", "type": "lighting"},
    {"year":  1902, "key": "radio", "type": "pasttime"},
    {"year":  1903, "key": "airplane", "type": "movement"},
    {"year":  1957, "key": "satellite", "type": "pasttime"},
    {"year":  1958, "key": "nuke", "type": "fighting"},
    {"year":  1972, "key": "led", "type": "lighting"},
    {"year":  1989, "key": "internet", "type": "pasttime"},
    {"year":  2018, "key": "scooter", "type": "movement"},
    {"year":  2070, "key": "space", "type": "movement"},
    {"year":  2100, "key": "vr", "type": "pasttime"},
    {"year":  2800, "key": "death_star", "type": "fighting"}
  ]
};
